-- Revert 000100: clear the official-issuer application URLs seeded on 2026-06-13.
UPDATE cards SET affiliate_url = NULL WHERE name IN (
  'Amex Gold Rewards',
  'Amex Platinum',
  'Amex Cobalt',
  'SimplyCash Card from American Express',
  'SimplyCash Preferred Card from American Express',
  'American Express Aeroplan Card',
  'American Express Platinum Business',
  'Marriott Bonvoy American Express Card',
  'American Express Green Card',
  'American Express Aeroplan Reserve',
  'Amex Aeroplan Business Reserve Card',
  'RBC Avion Visa Infinite',
  'RBC WestJet World Elite Mastercard',
  'RBC Avion Visa Infinite Privilege',
  'RBC British Airways Visa Infinite',
  'RBC ION+ Visa',
  'RBC Cash Back Preferred World Elite Mastercard',
  'RBC Avion Visa Platinum',
  'RBC WestJet Mastercard',
  'RBC Cash Back Mastercard',
  'Scotiabank Passport Visa Infinite',
  'Scotiabank Gold American Express',
  'Scotiabank Scene+ Visa',
  'Scotiabank Platinum American Express',
  'Scotia Momentum Mastercard No Fee',
  'Scotiabank Momentum No-Fee Visa',
  'Scotia Momentum Visa Infinite',
  'Scotiabank Value Visa Card',
  'CIBC Aventura Visa Infinite',
  'CIBC Aventura Visa Infinite Privilege',
  'CIBC Aeroplan Visa Infinite Privilege',
  'CIBC Costco Mastercard',
  'CIBC Dividend Visa Infinite',
  'CIBC Aventura Gold Visa',
  'CIBC Dividend Visa Card',
  'CIBC Aeroplan Visa Infinite',
  'CIBC Select Visa Card',
  'CIBC Dividend Platinum Visa',
  'BMO eclipse Visa Infinite Privilege',
  'BMO CashBack World Elite Mastercard',
  'BMO Ascend World Elite Mastercard',
  'BMO Cash Back Mastercard',
  'BMO eclipse Visa Infinite',
  'BMO Preferred Rate Mastercard',
  'TD Platinum Travel Visa',
  'TD Aeroplan Visa Infinite Privilege',
  'TD Aeroplan Visa Infinite',
  'TD Rewards Visa Card',
  'TD Aeroplan Visa Platinum',
  'TD Cash Back Visa Card',
  'TD First Class Travel Visa Infinite',
  'TD Cash Back Visa Infinite',
  'National Bank World Elite Mastercard',
  'National Bank Syncro Mastercard',
  'National Bank Allure Mastercard',
  'National Bank Platinum Mastercard',
  'PC Mastercard',
  'PC World Elite Mastercard',
  'PC Money Account',
  'Desjardins Odyssey World Elite Mastercard',
  'Desjardins Cash Back Visa',
  'Desjardins Odyssey Visa Gold',
  'Brim World Elite Mastercard',
  'Brim Mastercard',
  'MBNA True Line Mastercard',
  'MBNA Smart Cash Platinum Plus Mastercard',
  'MBNA Rewards World Elite Mastercard',
  'Triangle Mastercard',
  'Triangle World Elite Mastercard',
  'Neo Mastercard',
  'Neo World Elite Mastercard',
  'Home Trust Preferred Visa',
  'Wealthsimple Visa Infinite',
  'Rogers Red World Elite Mastercard',
  'Simplii Cash Back Visa',
  'Simplii Financial Visa Card',
  'Tangerine Money-Back Credit Card',
  'Tangerine World Mastercard'
);
