/* card-images.ts
 *
 * STRICT 1-to-1 card-name → RewardsCanada image URL map.
 *
 * Rules of this file:
 *   1. Every entry must point to art that genuinely depicts THAT specific card.
 *      No aliases that share an image with a different product (e.g. don't map
 *      "Aventura Visa Infinite" and "Aventura Visa Infinite Privilege" to the
 *      same .jpg — they are visually distinct cards).
 *   2. Variant-name aliases are OK only when they refer to the SAME card under
 *      different naming conventions (e.g. "Scotiabank Gold American Express"
 *      and "Scotiabank Gold Amex"). Marked with "// alias" comment.
 *   3. Cards we don't have unique art for: NO entry. They fall back to the
 *      issuer-themed gradient sprite in EditorialCardVisual / CreditCardVisual,
 *      which prints the actual card name on a unique-per-card colored gradient.
 *      That's better than showing the wrong art.
 *
 * Source: rewardscanada.ca publicly-displayed marketing imagery. If any issuer
 * asks for removal, delete the entry. The component fallback is automatic.
 */

const BASE = "https://www.rewardscanada.ca";

/* Manifest of locally-generated card art (generated by tools/scripts/generate-images.mjs).
 * Keys are slugs (lowercase, dashed). Values are file extensions ("png" | "webp").
 * When a card name resolves to a slug present here, the local URL wins over RewardsCanada. */
import LOCAL_MANIFEST from "@/public/cards/manifest.json";

function nameToSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

const RAW: Record<string, string> = {
  // ─── American Express ─────────────────────────────────────────
  "Amex Cobalt":                                  "/images/cardart/Amex/cobalt.jpg",
  "Amex Gold Rewards":                            "/images/cardart/Amex/amexgold.jpg",
  "Amex Platinum":                                "/images/cardart/Amex/platinum.png",
  "American Express Aeroplan Card":               "/images/cardart/Amex/amexaeroplan.jpg",
  "American Express Aeroplan Reserve":            "/images/cardart/Amex/amexreserve.png",
  "American Express Green Card":                  "/images/cardart/Amex/amexgreen.jpg",
  "American Express Platinum Business":           "/images/cardart/Amex/businessplat.png",
  "American Express Business Edge":               "/images/cardart/Amex/amexbizgold.png",
  "Amex Aeroplan Business Reserve Card":          "/images/cardart/Amex/amexreservebiz.jpg",
  "Marriott Bonvoy American Express Card":        "/images/cardart/Amex/bonvoy.png",
  "Marriott Bonvoy American Express Business Card":"/images/cardart/Amex/bonvoybiz.png",
  "SimplyCash Card from American Express":        "/images/cardart/Amex/simplycash-card.png",
  "SimplyCash Preferred Card from American Express":"/images/cardart/Amex/simplycash-preferred-card.jpg",
  // ─── BMO ──────────────────────────────────────────────────────
  "BMO CashBack World Elite Mastercard":          "/images/cardart/BMO/BMO CashBack World Elite Mastercard EN.png",
  /* BMO Eclipse VI / VIP — RC's `bmovi.png` / `bmovip.png` were confirmed wrong by user.
   * BMO's product pages are JS-rendered SPAs; static fetch can't reach the card art.
   * Falling back to the issuer-themed gradient sprite (which is unique per card name)
   * until we have a verified URL. */
  // ─── CIBC ─────────────────────────────────────────────────────
  "CIBC Aventura Visa Infinite":                  "/images/cardart/CIBC/aventura.jpg",
  "CIBC Aventura Gold Visa":                      "/images/cardart/CIBC/aventuragold.jpg",
  "CIBC Aventura Visa":                           "/images/cardart/CIBC/aventurabasic.png",
  "CIBC Dividend Visa Infinite":                  "/images/cardart/CIBC/dividendinf.png",
  "CIBC Dividend Platinum Visa":                  "/images/cardart/CIBC/dividendplat.png",
  "CIBC Dividend Visa":                           "/images/cardart/CIBC/dividend.png",
  // ─── National Bank ────────────────────────────────────────────
  "National Bank World Elite Mastercard":         "/images/cardart/NationalBank/worldelite.png",
  "National Bank World Mastercard":               "/images/cardart/NationalBank/world.png",
  "National Bank Platinum Mastercard":            "/images/cardart/NationalBank/platinum.png",
  "National Bank ECHO Cashback Mastercard":       "/images/cardart/NationalBank/echo.png",
  // ─── RBC ──────────────────────────────────────────────────────
  "RBC Avion Visa Infinite":                      "/images/cardart/RBC/card-avion.png",
  "RBC Avion Visa Infinite Privilege":            "/images/cardart/RBC/avionpriv.png",
  "RBC Avion Visa Business":                      "/images/cardart/RBC/avion-infinite-business.png",
  "RBC Cash Back Mastercard":                     "/images/cardart/RBC/rbccashback.png",
  "RBC Cash Back Preferred World Elite Mastercard":"/images/cardart/RBC/rbccashbackpref.png",
  "RBC Visa Platinum":                            "/images/cardart/RBC/rbcvisaplat.png",
  "RBC British Airways Visa Infinite":            "/images/cardart/RBC/ba.png",
  "RBC WestJet World Elite Mastercard":           "/images/cardart/RBC/WestJet RBC New.png",
  // ─── Scotiabank ──────────────────────────────────────────────
  "Scotiabank Momentum Visa Infinite":            "/images/cardart/Scotia/MomentumVisaInfinite1.jpg",
  "Scotia Momentum Visa Infinite":                "/images/cardart/Scotia/MomentumVisaInfinite1.jpg", // alias
  "Scotiabank Passport Visa Infinite":            "/images/cardart/Scotia/ScotiaPassportVisaInfinite.jpg",
  "Scotiabank Passport Visa Infinite Business":   "/images/cardart/Scotia/passportinfinitebiz.jpg",
  "Scotiabank Gold American Express":             "/images/cardart/Scotia/scotiagoldamex.png",
  "Scotiabank American Express":                  "/images/cardart/Scotia/scotiamex.png",
  "Scotiabank Platinum American Express":         "/images/cardart/Scotia/scotiaplatamex.png",
  "Scotia Momentum Mastercard":                   "/images/cardart/Scotia/momentummc.png",
  "Scotia Momentum Visa":                         "/images/cardart/Scotia/momentumvisa1.png",
  "Scotia Momentum No-Fee Visa":                  "/images/cardart/Scotia/momentumnofeevisa1.jpg",
  "Scotiabank Momentum No-Fee Visa":              "/images/cardart/Scotia/momentumnofeevisa1.jpg", // alias
  "Scotiabank Scene+ Visa":                       "/images/cardart/Scotia/scene.png",
  "Scene+ Visa":                                  "/images/cardart/Scotia/scene.png", // alias
  "Scene+ Visa Card":                             "/images/cardart/Scotia/scene.png", // alias
  // ─── TD ───────────────────────────────────────────────────────
  "TD Aeroplan Visa Infinite":                    "/images/cardart/TD/tdapinfnew.jpg",
  "TD Aeroplan Visa Infinite Privilege":          "/images/cardart/TD/apinfinitepriv.jpg",
  "TD Aeroplan Visa Platinum":                    "/images/cardart/TD/apvisaplat.jpg",
  "TD First Class Travel Visa Infinite":          "/images/cardart/TD/firstclass.jpg",
  "TD Cash Back Visa Infinite":                   "/images/cardart/TD/tdcashbackinf.jpg",
  // ─── MBNA ─────────────────────────────────────────────────────
  "MBNA Rewards World Elite Mastercard":          "/images/cardart/mbna/mbnarewardswe.png",
  "MBNA Rewards Platinum Mastercard":             "/images/cardart/mbna/mbnarewards.png",
  "MBNA Smart Cash World Mastercard":             "/images/cardart/mbna/smartcashworld.png",
  "MBNA Smart Cash Platinum Mastercard":          "/images/cardart/mbna/smartcash.png",
  "MBNA Smart Cash Platinum Plus Mastercard":     "/images/cardart/mbna/smartcash.png", // alias — same card, rebrand
  "MBNA Amazon.ca Rewards Mastercard":            "/images/cardart/mbna/mbnaamazon.jpg",
  // ─── Tangerine ────────────────────────────────────────────────
  "Tangerine Money-Back Credit Card":             "/images/cardart/Tangerine/tangerine.jpg",
  "Tangerine World Mastercard":                   "/images/cardart/Tangerine/tangerinewe.jpg",
  // ─── PC Financial / Rogers / Walmart / Simplii / Brim / Neo ──
  "PC Financial World Elite Mastercard":          "/images/cardart/PC/pcworldelite.png",
  "PC World Elite Mastercard":                    "/images/cardart/PC/pcworldelite.png", // alias
  /* Rogers WE / Red WE — RC's `rogerswe2.jpg` was confirmed wrong by user.
   * Rogers Bank's site is JS-rendered; falling back to gradient sprite. */
  "Walmart Rewards Mastercard":                   "/images/cardart/Walmart/walmart.png",
  "Walmart Rewards World Mastercard":             "/images/cardart/Walmart/walmartworld.png",
  "Simplii Financial Cash Back Visa":             "/images/cardart/Simplii/simplii.jpg",
  "Simplii Cash Back Visa":                       "/images/cardart/Simplii/simplii.jpg", // alias
  "Brim Mastercard":                              "/images/cardart/Brim/brim.png",
  /* Brim WE — RC's `brimwe.png` was confirmed wrong by user. Falling back to gradient sprite. */
  "Neo Credit Mastercard":                        "/images/cardart/Neo/neo.jpg",
  "Neo Mastercard":                               "/images/cardart/Neo/neo.jpg", // alias
  "Cathay Pacific Neo Mastercard":                "/images/cardart/Neo/cathay.jpg",
  "Neo United Mastercard":                        "/images/cardart/Neo/neo-united.jpg",
  "Neo World Elite Mastercard":                   "/images/cardart/Neo/neoworldelite.jpg",
  "Home Trust Preferred Visa":                    "/images/cardart/HomeTrust/hometrustpreferred.png",
  "Desjardins Odyssey World Elite Mastercard":    "/images/cardart/Desjardins/desjardinswemc.png",
};

/* Build a lookup that's case + whitespace + "scotiabank/scotia" + "amex/american express"
 * tolerant. Only matches names we have CONFIRMED unique art for. */
function normalize(s: string): string {
  return s
    .toLowerCase()
    .replace(/scotiabank/g, "scotia")
    .replace(/american express/g, "amex")
    .replace(/world elite/g, "we")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

const NORM_MAP: Map<string, string> = new Map(
  Object.entries(RAW).map(([k, v]) => [normalize(k), encodeURI(BASE + v)]),
);

export function cardImageUrl(name: string | undefined | null): string | null {
  if (!name) return null;
  /* 1. Local generated/scraped sprite wins (manifest is built by generate-images.mjs). */
  const slug = nameToSlug(name);
  const manifest = LOCAL_MANIFEST as Record<string, string>;
  const ext = manifest[slug];
  if (ext) return `/cards/${slug}.${ext}`;
  /* 2. RewardsCanada CDN — only for names with confirmed unique art. */
  const direct = RAW[name];
  if (direct) return encodeURI(BASE + direct);
  return NORM_MAP.get(normalize(name)) ?? null;
}

export const CARD_IMAGE_BASE = BASE;
